# Generated by Django 5.0.6 on 2024-06-13 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('1', 'Chest'), ('2', 'Back'), ('3', 'Triceps'), ('4', 'Forearm'), ('5', 'Legs'), ('6', 'Shoulders'), ('7', 'Biceps'), ('8', 'ABS'), ('9', 'Glutes'), ('10', 'Necks'), ('11', 'Warm Up'), ('12', 'Cardio')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
