# Generated by Django 5.0.6 on 2025-01-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_alter_exercise_options_exercise_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('1', 'Chest'), ('2', 'Back'), ('3', 'Triceps'), ('4', 'Forearm'), ('5', 'Legs'), ('6', 'Shoulders'), ('7', 'Biceps'), ('8', 'ABS'), ('9', 'Glutes'), ('10', 'Necks'), ('11', 'Warm Up'), ('12', 'Cardio'), ('13', 'Core'), ('14', 'Other')], max_length=100),
        ),
    ]
