# Generated by Django 5.0.6 on 2024-06-02 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('training_date', models.DateField()),
                ('exercises', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Triceps', 'Triceps'), ('Forearm', 'Forearm'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Biceps', 'Biceps'), ('ABS', 'ABS'), ('Glutes', 'Glutes'), ('Neck', 'Neck'), ('Warm-Up', 'Warm-Up'), ('Cardio', 'Cardio')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
