# Generated by Django 5.0.6 on 2024-06-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_training_delete_trainings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='category',
            field=models.CharField(choices=[('1', 'Chest'), ('2', 'Back'), ('3', 'Triceps'), ('4', 'Forearm'), ('5', 'Legs'), ('6', 'Shoulders'), ('7', 'Biceps'), ('8', 'ABS'), ('9', 'Glutes'), ('10', 'Necks'), ('11', 'Warm Up'), ('12', 'Cardio')], max_length=100),
        ),
    ]
