# Generated by Django 5.0.6 on 2024-06-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_exercise_reps'),
        ('trainings', '0005_remove_training_exercises_trainingexercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='exercises',
            field=models.ManyToManyField(related_name='trainings', through='trainings.TrainingExercise', to='exercises.exercise', verbose_name='Exercises'),
        ),
    ]
