# Generated by Django 5.0.6 on 2024-06-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_exercise_category'),
        ('trainings', '0007_alter_trainingexercise_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='training',
            name='category',
        ),
        migrations.AlterField(
            model_name='training',
            name='exercises',
            field=models.ManyToManyField(blank=True, default='', related_name='trainings', through='trainings.TrainingExercise', to='exercises.exercise', verbose_name='Exercises'),
        ),
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.ManyToManyField(blank=True, to='trainings.category', verbose_name='Category'),
        ),
    ]
