# Generated by Django 5.0.6 on 2024-06-13 16:05

from django.db import migrations, models


def populate_categories(apps, schema_editor):
    Category = apps.get_model("trainings", "Category")
    category_list = [
        "Chest",
        'Back',
        'Triceps',
        'Forearm',
        'Legs',
        'Shoulders',
        'Biceps',
        'ABS',
        'Glutes',
        'Necks',
        'Warm Up',
        'Cardio',
        'Core',
    ]
    for category in category_list:
        Category.objects.create(name=category)


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_remove_training_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='trainings', to='trainings.category', verbose_name='Category'),
        ),
        migrations.RunPython(populate_categories, reverse_code=migrations.RunPython.noop),
    ]
