# Generated by Django 5.0.6 on 2024-06-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0011_category_training_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='category',
        ),
        migrations.AddField(
            model_name='training',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='trainings', to='trainings.category', verbose_name='Categories'),
        ),
    ]
