# Generated by Django 5.0.6 on 2024-06-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0012_remove_training_category_training_categories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingexercise',
            unique_together=set(),
        ),
    ]
