# Generated by Django 5.0.6 on 2024-08-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0013_alter_trainingexercise_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='categories',
            new_name='category',
        ),
    ]
