# Generated by Django 5.0.6 on 2024-08-20 11:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0014_rename_categories_training_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingexercise',
            name='reps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, verbose_name="Reps (e.g., '10kg x 12')"), size=None),
        ),
    ]
