# Generated by Django 5.0.6 on 2024-08-29 16:53

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0015_alter_trainingexercise_reps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingexercise',
            name='reps',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, verbose_name="Reps (e.g., '10kg x 12')"), size=None),
        ),
    ]
