# Generated by Django 5.0.6 on 2024-11-14 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0016_alter_trainingexercise_reps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingexercise',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='trainingexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
