# Generated by Django 5.0.6 on 2024-12-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0018_trainingexercise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingexercise',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
