# Generated by Django 5.0.6 on 2024-12-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0019_trainingexercise_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingexercise',
            name='history',
            field=models.TextField(blank=True, default=''),
        ),
    ]
