# Generated by Django 5.0.6 on 2024-12-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0020_trainingexercise_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingexercise',
            name='history',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
