# Generated by Django 5.0.6 on 2024-12-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0022_trainingexercise_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingexercise',
            name='event_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
