# Generated by Django 5.0.6 on 2024-12-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0024_remove_trainingexercise_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingexercise',
            name='training_exercise_event_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
