# Generated by Django 5.0.6 on 2024-12-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0026_alter_trainingexercise_training_exercise_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingexercise',
            name='training_exercise_event_id',
        ),
        migrations.AddField(
            model_name='training',
            name='is_copy',
            field=models.BooleanField(default=False),
        ),
    ]
