# Generated by Django 5.0.6 on 2024-12-20 18:42

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0027_remove_trainingexercise_training_exercise_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingexercise',
            name='reps_proposed',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, verbose_name="Reps (e.g., '10kg x 12')"), default=[], size=None),
            preserve_default=False,
        ),
    ]
