# Generated by Django 5.0.6 on 2024-06-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendary',
            new_name='Event',
        ),
    ]
