# Generated by Django 5.0.6 on 2024-06-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0002_rename_calendary_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
